import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SidebarProfile from "../components/SidebarProfile";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navItems = [
  { label: "Dashboard", active: true },
  { label: "Cases", active: false },
  { label: "Campaigns", active: false },
  { label: "Reports", active: false },
  { label: "Settings", active: false },
];

function NavIcon({ name }) {
  const common = {
    width: 16,
    height: 16,
    viewBox: "0 0 24 24",
    fill: "none",
    stroke: "currentColor",
    strokeWidth: 1.5,
    strokeLinecap: "round",
    strokeLinejoin: "round",
    "aria-hidden": true,
  };

  if (name === "Dashboard") {
    return (
      <svg {...common}>
        <rect x="3" y="3" width="7" height="9" rx="1" />
        <rect x="14" y="3" width="7" height="5" rx="1" />
        <rect x="14" y="12" width="7" height="9" rx="1" />
        <rect x="3" y="16" width="7" height="5" rx="1" />
      </svg>
    );
  }

  if (name === "Cases") {
    return (
      <svg {...common}>
        <path d="M9 3h6l1 3h4v14H4V6h4z" />
      </svg>
    );
  }

  if (name === "Campaigns") {
    return (
      <svg {...common}>
        <circle cx="12" cy="12" r="3" />
        <path d="M12 3v2M12 19v2M3 12h2M19 12h2M5.6 5.6l1.4 1.4M17 17l1.4 1.4M18.4 5.6 17 7M7 17l-1.4 1.4" />
      </svg>
    );
  }

  if (name === "Reports") {
    return (
      <svg {...common}>
        <path d="M6 3h9l5 5v13H6z" />
        <path d="M15 3v5h5M8 13h8M8 17h5" />
      </svg>
    );
  }

  return (
    <svg {...common}>
      <circle cx="12" cy="12" r="3" />
      <path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4" />
    </svg>
  );
}

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full bg-canvas text-ink antialiased`}
    >
      <body className="min-h-full bg-canvas text-ink">
        <div className="flex min-h-full">
          <aside className="sticky top-0 flex h-screen w-[220px] shrink-0 flex-col justify-between border-r border-edge bg-surface px-4 py-5">
            <div>
              <div className="mb-8 text-sm font-medium tracking-wide text-ink">
                Email Forensics
              </div>
              <nav className="flex flex-col gap-1">
                {navItems.map((item) => (
                  <a
                    key={item.label}
                    href="#"
                    className={`flex items-center gap-2 rounded-md px-2 py-2 text-sm ${
                      item.active
                        ? "bg-canvas text-accent"
                        : "text-dim"
                    }`}
                  >
                    <NavIcon name={item.label} />
                    {item.label}
                  </a>
                ))}
              </nav>
            </div>
            <div className="pt-4 border-t border-edge/60">
              <SidebarProfile />
            </div>
          </aside>
          <main className="min-w-0 flex-1 bg-canvas">{children}</main>
        </div>
      </body>
    </html>
  );
}
